# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-28 09:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20160526_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2016, 5, 28, 9, 6, 13, 673314, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
